chore: improve gem release script

diff --git a/bin/release b/bin/release
--- a/bin/release
+++ b/bin/release
@@ -3,5 +3,15 @@
 rake build
 
 printf "\n✅ Lookbook v${1/-/.} gem built."
-printf "\n🚨 You must now push the gem to Rubygems to complete the release. MFA code is required! 🚨"
-printf "\n\n👉 gem push pkg/lookbook-${1/-/.}.gem --otp MFA_CODE_HERE\n\n"
+printf "\n\n💎 Pushing to RubyGems. Please provide MFA token:\n"
+
+read token
+
+gem push pkg/lookbook-${1/-/.}.gem --otp ${token}
+
+if [ $? -eq 0 ]; 
+then 
+  printf "\n✅ Successfully released Lookbook v${1/-/.}"
+else 
+  printf "\n❌ Error pushing gem to Rubygems"
+fi
